### ISSUE TITLE
Installtool error

### ISSUE THREAD

**Issue by haukehaller** [netresearch/t3x-nr_dam_falmigration#2]
The Upgrade Wizard doesn't work here and give an error warning:
Call to a member function includeLLFile() on a non-object in /html/typo3/typo3_src-6.2.17/typo3/sysext/extensionmanager/Classes/Utility/FileHandlingUtility.php on line 46 

Whithout installed nr_dam_falmigration the updatewizard works. 
I tried Version 1.0.0 and 1.1.0

**Comment by copitz** [comment]
Hi Hauke,

The error doesn't seem to have directly to do with this extension - googling for "Call to a member function includeLLFile() on a non-object" brought me f.i. to http://www.typo3forum.net/discussion/49989/update-von-4-4-6-auf-4-5-0-bringt-fehler

May it be that you have "register_globals" on?

**Comment by frank79a** [comment]
Hi, I have the same problem as haukehaller. register_globals is off.

Any ideas?

**Comment by Gitsko** [comment]
Is meanwhile no longer comprehensible, i will close this issue.
